export type CharacterHistoricalData = {
    AvatarURL: string,
    ClassID: number,
    ClassRankGroupID: number,
    CurrentEXP: bigint,
    DateLabel: string,
    EXPDifference: bigint,
    EXPToNextLevel: bigint,
    ImportTime: number,
    Level: number,
    Name: string,
    ServerID: number,
    ServerMergeID: number,
    TotalOverallEXP: bigint,
}

export type rawCharacterData = {
    AchievementPoints: number
    AchievementRank: number,
    CharacterImageURL: string,
    Class: string,
    ClassRank: number,
    EXP: bigint,
    EXPPercent: number,
    GlobalRanking: number,
    GraphData: CharacterHistoricalData[],
    Guild: string,
    LegionCoinsPerDay: number,
    LegionLevel: number,
    LegionPower: bigint,
    LegionRank: number,
    Level: number,
    Name: string,
    Server: string,
    ServerClassRanking: number,
    ServerRank: number,
    ServerSlug: string,
}

export type parsedCharacterData = {
    Name: string,
    Class: string,
    CharacterImageURL: string,
    Server: string,
    Level: number,
    EXP: bigint,
    EXPPercent: number,
    WeekAverage: bigint,
    FortnightAverage: bigint,
    GlobalRanking: number,
    ServerRank: number,
    LegionLevel: number,
    LegionRank: number,
    LegionPower: bigint,
    ImportTime: Date | undefined,
}
